POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
       
    "date": "2019-08-05",
    "type": "OccupationalHealthcare",
    "specialist": "MD House",
    "diagnosisCodes": [],
    "description": "patient dead",
    "healthCheckRating": 3
}

